name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run rebuild

      - name: Package and publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then npx electron-builder -l --publish always; fi
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then npx electron-builder -w --publish always; fi
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then npx electron-builder -m --publish always; fi
