name: Test Builds

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-build:
    name: Test Build - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: macos-latest
            platform: macOS
          - os: windows-latest
            platform: Windows
          - os: ubuntu-latest
            platform: Linux
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build TypeScript (main process)
        run: npm run build:main
      
      - name: Build Webpack (renderer)
        run: npm run build
      
      - name: Test compilation success
        run: |
          echo "✅ Build successful on ${{ matrix.platform }}"
          ls -la dist/
      
      - name: Upload build artifacts (for debugging)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failed-build-${{ matrix.os }}
          path: |
            dist/
            *.log
          retention-days: 7

